services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-notebooklm-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  qdrant_storage:
